import XCTest
@testable import DialBridge

/// Proves the iOS side agrees with the browser.
///
/// The fixtures below were produced by the browser extension's own
/// `crypto.js` running under Web Crypto — not by this code, and not by hand.
/// If CryptoKit and Web Crypto ever disagree about the wire format, this test
/// fails; without it, the disagreement would surface as an app that silently
/// drops every notification, which is a miserable thing to debug on a phone.
final class CryptoTests: XCTestCase {

    // Generated by: tools/crypto-interop/encrypt.js in the DialBridge repo.
    private let key = "c3VD5JAO6gvg-Ye57lp0rbbm8a_rZU6pDA8RF3FTtl4"
    private let payload = "qvkpGXYXJYi9ZA6FCEBNKkk7jBSfAgOyoGiOodvmmyGODvygWde5od4"
    private let expected = "+306900000000"

    func testDecryptsCiphertextProducedByTheBrowser() {
        let result = Crypto.decrypt(payload: payload, keyBase64URL: key)
        XCTAssertEqual(result, expected, "CryptoKit disagrees with Web Crypto's AES-GCM output")
    }

    func testRejectsATamperedMessage() {
        // Flip one character in the middle of the ciphertext. AES-GCM must
        // refuse it rather than produce plausible rubbish — that property is
        // what lets the app treat a successful decryption as proof the message
        // came from the paired browser.
        var characters = Array(payload)
        let middle = characters.count / 2
        characters[middle] = characters[middle] == "A" ? "B" : "A"
        let tampered = String(characters)

        XCTAssertNil(
            Crypto.decrypt(payload: tampered, keyBase64URL: key),
            "a tampered message must not decrypt"
        )
    }

    func testRejectsTheWrongKey() {
        let otherKey = Crypto.newKey()
        XCTAssertNil(
            Crypto.decrypt(payload: payload, keyBase64URL: otherKey),
            "a message must not decrypt under a key it was not sealed with"
        )
    }

    func testRejectsMalformedInput() {
        XCTAssertNil(Crypto.decrypt(payload: "", keyBase64URL: key))
        XCTAssertNil(Crypto.decrypt(payload: "not base64url!!", keyBase64URL: key))
        XCTAssertNil(Crypto.decrypt(payload: payload, keyBase64URL: "tooshort"))
        // Shorter than a nonce plus a tag: nothing could be inside it.
        XCTAssertNil(Crypto.decrypt(payload: "AAAA", keyBase64URL: key))
    }

    func testNewKeyIsA256BitValue() {
        let generated = Crypto.newKey()
        let raw = Data(base64URLEncoded: generated)
        XCTAssertEqual(raw?.count, 32, "AES-256 needs exactly 32 bytes")
        XCTAssertNotEqual(generated, Crypto.newKey(), "keys must not repeat")
    }

    func testPhoneNumberShapeCheck() {
        XCTAssertTrue(Crypto.looksLikePhoneNumber("+306900000000"))
        XCTAssertTrue(Crypto.looksLikePhoneNumber("2107654321"))
        XCTAssertFalse(Crypto.looksLikePhoneNumber("12345"))          // too short
        XCTAssertFalse(Crypto.looksLikePhoneNumber("+30 690 000"))    // spaces
        XCTAssertFalse(Crypto.looksLikePhoneNumber("rm -rf /"))       // not a number
        XCTAssertFalse(Crypto.looksLikePhoneNumber(""))
    }
}
